### PR TITLE
Make white color blue to fix both white/black terminals.

### PR DESCRIPTION
**Pull request by clemens-tolboom**
This is just a proposal for another color. In which we learned `$white` should probably be named semantic. I just changed the color and not the name.

I guess we should change the vars

```php
$white -> $info
$yellow -> $notice
$red -> $error
```

What do you think?

### CODE REVIEW

**Comment by clemens-tolboom** [comment]
This should fix #28

**Comment by clemens-tolboom** [comment]
## Blue is bad on black terminal

wp-generator-console-output-black

## White is bad on white terminal

wp-generator-console-output

**Comment by Mte90** [comment]
As example I am using a black terminal with green color.
As I written on https://github.com/WPBP/generator/issues/28 we can do 2 colors scheme.
I think that I can close this pr, add the code for rename all the variables about colors and later a theme system by a flag.

**Comment by clemens-tolboom** [comment]
I've added (force pushed) a theme aware version. It was a little weird with the `global vars`. __--help__ is is 'theme' unaware. Did I swapped too many lines?

**Comment by Mte90** [comment]
The code seems good, I will try asap :-)

**Comment by Mte90** [comment]
Tried and works pretty well, I think that we need an alert about the color scheme in use  but I can add on the help output :-)
Thanks for the code, I will release a new version asap!

**Pull request merged**
